plugins {
    id 'com.android.application'
    id 'com.google.gms.google-services'
}

android {
    namespace 'com.acaida7.painel'
    compileSdk 36

    defaultConfig {
        applicationId 'com.acaida7.painel'
        minSdk 23
        targetSdk 35
        versionCode Integer.parseInt(project.property('versionCode').toString())
        versionName project.property('versionName').toString()
    }

    signingConfigs {
        release {
            def keystorePath = System.getenv('KEYSTORE_FILE')
            if (keystorePath) {
                storeFile file(keystorePath)
                storePassword System.getenv('KEYSTORE_PASSWORD')
                keyAlias System.getenv('KEY_ALIAS')
                keyPassword System.getenv('KEY_PASSWORD')
            }
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
        }
    }

    lint {
        disable 'InvalidFragmentVersionForActivityResult'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.core:core:1.17.0'
    implementation 'androidx.activity:activity:1.11.0'
    implementation platform('com.google.firebase:firebase-bom:34.19.0')
    implementation 'com.google.firebase:firebase-messaging'
}
